# Generated by Django 3.0.6 on 2020-05-30 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1_index', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
    ]
