# Generated by Django 3.0.6 on 2020-06-01 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1_index', '0005_auto_20200531_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='achievement',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='education',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='education',
            name='uni_short_descript',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='education',
            name='university',
            field=models.CharField(max_length=70),
        ),
    ]
