# Generated by Django 3.0.6 on 2020-06-19 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1_index', '0007_contact_me'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interests',
            options={'verbose_name_plural': 'Interests'},
        ),
    ]
