# Generated by Django 2.2.8 on 2020-09-16 09:57

import cloudinary.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_me',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=70)),
                ('message', models.TextField(max_length=700)),
                ('sent_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myimage', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myskill', models.CharField(max_length=100)),
                ('completionper', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('work', models.CharField(max_length=30)),
                ('birthday', models.DateTimeField()),
                ('website', models.CharField(max_length=110)),
                ('email', models.EmailField(max_length=60)),
                ('location', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=14, validators=[django.core.validators.RegexValidator(message="phone number must be entered in the format:'+2547*******'", regex='^\\+?1?\\d{9,15}?$')])),
                ('prof_image', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1_index.ProfileImage')),
            ],
        ),
        migrations.CreateModel(
            name='Lang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_title', models.CharField(default='English', max_length=11)),
                ('language_status', models.CharField(default='fluent', max_length=6)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1_index.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interst_title', models.CharField(default='swimming', max_length=20)),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1_index.Profile')),
            ],
            options={
                'verbose_name_plural': 'Interests',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_experience', models.CharField(max_length=13)),
                ('task', models.CharField(max_length=30)),
                ('company', models.CharField(max_length=30)),
                ('exp_short_descript', models.TextField(max_length=50)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1_index.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_study', models.CharField(max_length=13)),
                ('achievement', models.CharField(max_length=80)),
                ('institution', models.CharField(max_length=70)),
                ('uni_short_descript', models.TextField(max_length=200)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1_index.Profile')),
            ],
        ),
    ]
