# Generated by Django 3.0.6 on 2020-06-22 20:53

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1_index', '0010_skill_completionper'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='university',
            new_name='institution',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='prof_image',
        ),
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
