# Generated by Django 3.0.6 on 2020-05-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myinfo',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='myinfo',
            name='title',
            field=models.CharField(choices=[('MR', 'MR.'), ('MRS', 'MRS.')], max_length=100),
        ),
    ]
