# Generated by Django 3.0.6 on 2020-05-30 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1_index', '0002_remove_profile_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='lang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1_index.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='interests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1_index.Profile')),
            ],
        ),
    ]
