# Generated by Django 3.0.6 on 2020-05-31 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1_index', '0004_auto_20200530_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interests',
            name='interst_title',
            field=models.CharField(default='swimming', max_length=20),
        ),
        migrations.AlterField(
            model_name='lang',
            name='language_status',
            field=models.CharField(default='fluent', max_length=6),
        ),
        migrations.AlterField(
            model_name='lang',
            name='language_title',
            field=models.CharField(default='English', max_length=11),
        ),
        migrations.AlterField(
            model_name='profile',
            name='work',
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_experience', models.CharField(max_length=13)),
                ('task', models.CharField(max_length=30)),
                ('company', models.CharField(max_length=30)),
                ('exp_short_descript', models.TextField(max_length=50)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1_index.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500)),
                ('year_of_study', models.CharField(max_length=13)),
                ('achievement', models.CharField(max_length=30)),
                ('university', models.CharField(max_length=20)),
                ('uni_short_descript', models.TextField(max_length=50)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1_index.Profile')),
            ],
        ),
    ]
