# Generated by Django 3.0.6 on 2020-06-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1_index', '0008_auto_20200619_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myskill', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='education',
            name='description',
        ),
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.TextField(default='hello', max_length=1000),
            preserve_default=False,
        ),
    ]
