# Generated by Django 3.0.6 on 2020-06-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1_index', '0009_auto_20200621_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='completionper',
            field=models.IntegerField(default=75),
            preserve_default=False,
        ),
    ]
