# Generated by Django 3.0.6 on 2020-06-23 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1_index', '0011_auto_20200622_2053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='photo',
            new_name='prof_image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='description',
        ),
    ]
